# Generated by Django 4.2.8 on 2023-12-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatmug_main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="average_response_time",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="fulfillment_rate",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="on_time_delivery_rate",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="quality_rating_avg",
            field=models.FloatField(default=None, null=True),
        ),
    ]
