# Generated by Django 4.2.8 on 2023-12-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fatmug_main", "0002_alter_vendor_average_response_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="average_response_time",
            field=models.FloatField(db_comment="in Minutes", default=None, null=True),
        ),
    ]
